name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - "test-older-version"
    paths-ignore:
      - "docs/**"

jobs:
  run:
    runs-on: ubuntu-latest
    container:
      image: ministryofjustice/tech-docs-github-pages-publisher:1.4
    steps:
    - uses: actions/checkout@v4
    - name: Publish
      run: /publishing-scripts/publish.sh
